cat node_modules/angular/angular.min.js \
  node_modules/angular-route/angular-route.min.js \
  node_modules/ui-router-extras/release/modular/ct-ui-router-extras.core.js \
  node_modules/ui-router-extras/release/modular/ct-ui-router-extras.future.js \
  node_modules/angular-i18n/angular-locale_en-us.js \
  node_modules/angulartics/dist/angulartics.min.js \
  node_modules/angulartics/dist/angulartics-ga.min.js \
  node_modules/angular-animate/angular-animate.min.js \
  node_modules/angular-bootstrap-npm/dist/angular-bootstrap-tpls.js \
  node_modules/ui-select/dist/select.js \
  node_modules/angular-bootstrap-datetimepicker/src/js/datetimepicker.js \
  node_modules/angular-cookie/angular-cookie.min.js \
  node_modules/ng-file-upload/dist/angular-file-upload-shim.min.js \
  node_modules/ng-file-upload/dist/angular-file-upload.min.js \
  node_modules/angular-growl-v2/build/angular-growl.min.js \
  node_modules/angular-resource/angular-resource.min.js \
  node_modules/angular-sanitize/angular-sanitize.js \
  node_modules/angular-timeago/src/timeAgo.js \
  node_modules/angular-ui-router/release/angular-ui-router.min.js \
  node_modules/angular-translate/dist/angular-translate.min.js \
  node_modules/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js \
  app/vendor/messageformat/messageformat.js \
  app/vendor/messageformat/locales.js \
  node_modules/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.min.js \
  > build/angular.js
