FORMAT: 1A
HOST: http://localhost:8999

# madison

Madison is a government policy co-creation platform that opens up laws
and legislation previously off-limits to individuals and the Internet
community.

# Group Documents

## Single Document [/docs/{doc_id}]

+ Parameters
    + doc_id: `1` (required, number)

### Get Single Document [GET]

+ Response 200 (application/json)

    + Attributes (Document)

## Documents Collection [/docs]

Due to the length of the documents involved, the documents collection
endpoints do not return the content of the documents.  Please use the
Document Object if you need to retrieve the content.

### List Documents [GET]

+ Response 200 (application/json)

    + Attributes (array[Document])

### Create A Document [POST]

+ Request (application/json)

    + Attributes (New Document)

+ Response 200 (application/json)

    + Attributes
        + doc (Document, required)

# Data Structures

## Document

+ id: `1` (number, required)
+ title: `Constitution of the United States` (string, required)
+ slug: `constitution` (string, required) - URL slug
+ thumbnail: `/img/doc-70/default.jpeg` (string, nullable)
+ created_at: `2014-06-10T13:02:26+00:00`(string)
+ updated_at: `2015-09-17T14:38:47+00:00` (string)
+ deleted_at: `2015-09-17T14:38:47+00:00` (string, nullable)
+ private: `false` (boolean)
+ is_template: `0` (number)
+ featured: `true` (boolean)
+ url: `https://mymadison.io/docs/constitution` (string)
+ comment_count: `0` (number)
+ annotation_count: `20` (number)
+ annotation_comment_count: `3` (number)
+ user_count: `12` (number)
+ support: `11` (number)
+ oppose: `1` (number)
+ categories (array[Category])
+ sponsor (array[Sponsor])
+ statuses (array[Status])
+ dates (array[Date])
+ introtext (string, optional, nullable)

## Document Content

+ doc_id: `1` (number, required)
+ content (string, required)
+ page (number, required)

## New Document

+ title: `Fancy New Legislation` (string, required)
+ group_id: `1` (number, optional)
+ user_id: `1` (number, optional)

## Category

+ id: `1` (number, required)
+ name: `congressional` (string, required)

## Date

## Sponsor

+ display_name: `Person or Group Name` (string, required)

## Status

